name: Fypper-Deploy

on:
  push: 
    tags: 
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DOCKER_USER_NAME }} 
        # Container registry password
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Container registry server url
        login-server: https://fyyper.azurecr.io

    - name: Building Docker Image
      working-directory: ./webapp
      run: docker build .. -f ./Dockerfile -t fyyper.azurecr.io/atlcc:latest

    - name: Push the Image
      working-directory: ./webapp 
      run: docker push fyyper.azurecr.io/atlcc:latest
